import '../models/user_profile.dart';
import '../models/conversation.dart';

class MockDataService {
  static final List<UserProfile> profiles = [
    UserProfile(
      id: '1',
      firstName: 'Sarah',
      dateOfBirth: DateTime(1985, 3, 15),
      city: 'Austin',
      state: 'Texas',
      gender: 'Female',
      relationshipStatus: 'Single',
      photoUrls: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop'],
      aboutMe: 'Nature lover and avid reader. Recently relocated to Austin and looking to meet genuine people for friendship and maybe more. Love hiking, cooking, and exploring local coffee shops.',
      lookingFor: ['Friendship', 'Local Friends', 'Dating'],
      interests: ['Hiking', 'Reading', 'Cooking', 'Travel', 'Photography'],
      lifeSituation: ['Recently Relocated', 'Starting Over'],
      emailVerified: true,
      phoneVerified: true,
      selfieVerified: true,
      isOnline: true,
      lastActive: DateTime.now(),
    ),
    UserProfile(
      id: '2',
      firstName: 'James',
      dateOfBirth: DateTime(1978, 7, 22),
      city: 'Denver',
      state: 'Colorado',
      gender: 'Male',
      relationshipStatus: 'Divorced',
      photoUrls: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop'],
      aboutMe: 'Army veteran and proud dad of two amazing kids. Life gave me a fresh start and I am embracing it. Love the outdoors, music, and good conversation over coffee.',
      lookingFor: ['Friendship', 'Dating', 'Activity Partner'],
      interests: ['Hiking', 'Music', 'Fitness', 'Cooking', 'Sports'],
      lifeSituation: ['Divorced', 'Veteran', 'Single Parent'],
      emailVerified: true,
      phoneVerified: true,
      isOnline: false,
      lastActive: DateTime.now().subtract(const Duration(hours: 2)),
    ),
    UserProfile(
      id: '3',
      firstName: 'Maria',
      dateOfBirth: DateTime(1990, 11, 8),
      city: 'Portland',
      state: 'Oregon',
      gender: 'Female',
      relationshipStatus: 'Single',
      photoUrls: ['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=400&auto=format&fit=crop'],
      aboutMe: 'Creative soul who loves art, yoga, and trying every restaurant in the city. Looking for genuine connections — no games, just real people.',
      lookingFor: ['Friendship', 'Long-Term Relationship', 'Local Friends'],
      interests: ['Yoga', 'Art', 'Cooking', 'Photography', 'Travel'],
      lifeSituation: ['Starting Over'],
      emailVerified: true,
      selfieVerified: true,
      isOnline: true,
      lastActive: DateTime.now(),
    ),
    UserProfile(
      id: '4',
      firstName: 'Robert',
      dateOfBirth: DateTime(1955, 5, 30),
      city: 'Scottsdale',
      state: 'Arizona',
      gender: 'Male',
      relationshipStatus: 'Widowed',
      photoUrls: ['https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=400&auto=format&fit=crop'],
      aboutMe: 'Retired engineer enjoying life in the desert. My kids are grown, and I am ready to meet someone to share adventures with. Love golf, travel, and wine tasting.',
      lookingFor: ['Dating', 'Travel Partner', 'Open To Anything'],
      interests: ['Travel', 'Wine Tasting', 'Gardening', 'Photography', 'Reading'],
      lifeSituation: ['Widowed', 'Retired', 'Empty Nester'],
      emailVerified: true,
      phoneVerified: true,
      selfieVerified: true,
      idVerified: true,
      isOnline: false,
      lastActive: DateTime.now().subtract(const Duration(days: 1)),
    ),
    UserProfile(
      id: '5',
      firstName: 'Lisa',
      dateOfBirth: DateTime(1982, 9, 12),
      city: 'Nashville',
      state: 'Tennessee',
      gender: 'Female',
      relationshipStatus: 'Divorced',
      photoUrls: ['https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400&auto=format&fit=crop'],
      aboutMe: 'Music-loving single mom navigating a new chapter. I believe the best connections start with friendship. Let us grab coffee and see where it goes!',
      lookingFor: ['Friendship', 'Dating', 'Local Friends'],
      interests: ['Music', 'Dancing', 'Cooking', 'Movies', 'Volunteering'],
      lifeSituation: ['Divorced', 'Single Parent'],
      emailVerified: true,
      phoneVerified: true,
      isOnline: true,
      lastActive: DateTime.now(),
    ),
    UserProfile(
      id: '6',
      firstName: 'David',
      dateOfBirth: DateTime(1988, 1, 25),
      city: 'Chicago',
      state: 'Illinois',
      gender: 'Male',
      relationshipStatus: 'Single',
      photoUrls: ['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop'],
      aboutMe: 'Tech professional by day, board game enthusiast by night. Recently moved to Chicago and looking for genuine friendships. Open to whatever life brings.',
      lookingFor: ['Friendship', 'Activity Partner', 'Open To Anything'],
      interests: ['Board Games', 'Technology', 'Fitness', 'Movies', 'Cooking'],
      lifeSituation: ['Recently Relocated'],
      emailVerified: true,
      isOnline: false,
      lastActive: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    UserProfile(
      id: '7',
      firstName: 'Patricia',
      dateOfBirth: DateTime(1960, 4, 17),
      city: 'San Diego',
      state: 'California',
      gender: 'Female',
      relationshipStatus: 'Widowed',
      photoUrls: ['https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=400&auto=format&fit=crop'],
      aboutMe: 'Retired teacher ready for new adventures. Love gardening, crafts, and volunteering at the local animal shelter. Looking for travel companions and real connections.',
      lookingFor: ['Travel Partner', 'Friendship', 'Local Friends'],
      interests: ['Gardening', 'Crafts', 'Volunteering', 'Travel', 'Pets'],
      lifeSituation: ['Widowed', 'Retired', 'Empty Nester'],
      emailVerified: true,
      phoneVerified: true,
      selfieVerified: true,
      isOnline: true,
      lastActive: DateTime.now(),
    ),
    UserProfile(
      id: '8',
      firstName: 'Michael',
      dateOfBirth: DateTime(1975, 8, 3),
      city: 'Miami',
      state: 'Florida',
      gender: 'Male',
      relationshipStatus: 'Divorced',
      photoUrls: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop'],
      aboutMe: 'Disabled veteran finding my stride again. Love the beach, fishing, and a good book. Looking for people who understand that life is about the journey.',
      lookingFor: ['Friendship', 'Dating', 'Online Friends'],
      interests: ['Sports', 'Reading', 'Fitness', 'Photography', 'Music'],
      lifeSituation: ['Divorced', 'Veteran', 'Disabled'],
      emailVerified: true,
      phoneVerified: true,
      isOnline: false,
      lastActive: DateTime.now().subtract(const Duration(hours: 8)),
    ),
  ];

  static final List<Conversation> conversations = [
    Conversation(
      id: 'c1',
      otherUserId: '1',
      otherUserName: 'Sarah',
      otherUserPhoto: profiles[0].photoUrls.first,
      lastMessage: 'That hiking trail sounds amazing! When are you free?',
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 15)),
      unreadCount: 2,
      isOnline: true,
    ),
    Conversation(
      id: 'c2',
      otherUserId: '5',
      otherUserName: 'Lisa',
      otherUserPhoto: profiles[4].photoUrls.first,
      lastMessage: 'I would love to check out that new coffee place downtown!',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 1)),
      unreadCount: 0,
      isOnline: true,
    ),
    Conversation(
      id: 'c3',
      otherUserId: '2',
      otherUserName: 'James',
      otherUserPhoto: profiles[1].photoUrls.first,
      lastMessage: 'Thanks for the recommendation. Will check it out!',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 4)),
      unreadCount: 0,
      isOnline: false,
    ),
    Conversation(
      id: 'c4',
      otherUserId: '7',
      otherUserName: 'Patricia',
      otherUserPhoto: profiles[6].photoUrls.first,
      lastMessage: 'Hello! I saw we share a love for gardening.',
      lastMessageTime: DateTime.now().subtract(const Duration(days: 1)),
      unreadCount: 1,
      isRequest: true,
      isOnline: true,
    ),
  ];

  static List<ChatMessage> getMessages(String conversationId) {
    final now = DateTime.now();
    return [
      ChatMessage(id: 'm1', senderId: 'other', text: 'Hey! I noticed we both love hiking. Have you tried any trails nearby?', timestamp: now.subtract(const Duration(hours: 3)), isRead: true),
      ChatMessage(id: 'm2', senderId: 'me', text: 'Hi! Yes, I recently did the Barton Creek trail — it was beautiful!', timestamp: now.subtract(const Duration(hours: 2, minutes: 45)), isRead: true),
      ChatMessage(id: 'm3', senderId: 'other', text: 'Oh I have been wanting to try that one! How long was the hike?', timestamp: now.subtract(const Duration(hours: 2, minutes: 30)), isRead: true),
      ChatMessage(id: 'm4', senderId: 'me', text: 'About 3 hours round trip. The views are worth it!', timestamp: now.subtract(const Duration(hours: 2)), isRead: true),
      ChatMessage(id: 'm5', senderId: 'other', text: 'That hiking trail sounds amazing! When are you free?', timestamp: now.subtract(const Duration(minutes: 15)), isRead: false),
    ];
  }

  static final List<Report> reports = [
    Report(
      id: 'r1',
      reporterId: '3',
      reportedUserId: '99',
      reportedUserName: 'SuspiciousUser',
      reason: 'Spam',
      details: 'Sending repeated promotional messages',
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    Report(
      id: 'r2',
      reporterId: '5',
      reportedUserId: '98',
      reportedUserName: 'FakeProfile123',
      reason: 'Fake Profile',
      details: 'Photos appear to be stolen from a celebrity',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
  ];

  static const List<String> usStates = [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
    'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
    'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
    'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
    'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
    'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
    'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
    'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
    'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
    'West Virginia', 'Wisconsin', 'Wyoming',
  ];
}
